version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # API REST
    volumes:
      - qdrant_data:/qdrant/storage

  fastapi:
    build:
      context: .           # Le répertoire racine où se trouve le Dockerfile
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - .:/app
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

volumes:
  qdrant_data:
